/* ---------------- level ladder ---------------- */
export const LEVELS = [
  { key: "listen", name: "Super Ears", emoji: "👂", hint: "Tap what you hear" },
  { key: "lab", name: "Sound Lab", emoji: "🧪", hint: "Learn the sound" },
  { key: "words", name: "Word Quest", emoji: "🗺️", hint: "Say the words" },
  { key: "sentences", name: "Silly Sentences", emoji: "😜", hint: "Say silly stuff" },
  { key: "story", name: "Story Time", emoji: "📖", hint: "Tell the tale" },
];

export const MAX_STARS = { listen: 5, lab: 5, words: 9, sentences: 3, story: 4 };
export const WORLD_MAX = 26;

/* ---------------- world content ---------------- */
export const WORLDS = [
  {
    id: "r",
    sound: "R",
    name: "Rocket Racetrack",
    emoji: "🚀",
    color: "#FF5D73",
    coach: "Bigger tiger growl — pull your tongue back!",
    cue: {
      title: "The Tiger Growl",
      lines: [
        "Pull your tongue back — don't touch your teeth!",
        "Growl like a tiger: grrr… rrr!",
        "Keep your lips still. The tongue does the work.",
      ],
      drills: ["rah", "ray", "ree", "roh", "roo"],
    },
    listen: [
      { say: "ring", options: [{ w: "ring", e: "💍" }, { w: "wing", e: "🪽" }] },
      { say: "rock", options: [{ w: "rock", e: "🪨" }, { w: "lock", e: "🔒" }] },
      { say: "red", options: [{ w: "red", e: "🔴" }, { w: "bed", e: "🛏️" }] },
      { say: "rice", options: [{ w: "rice", e: "🍚" }, { w: "mice", e: "🐭" }] },
      { say: "rat", options: [{ w: "rat", e: "🐀" }, { w: "hat", e: "🎩" }] },
    ],
    words: {
      start: [
        { w: "rabbit", e: "🐰" },
        { w: "rocket", e: "🚀" },
        { w: "rainbow", e: "🌈" },
        { w: "robot", e: "🤖" },
        { w: "ring", e: "💍" },
        { w: "rose", e: "🌹" },
        { w: "rain", e: "🌧️" },
        { w: "road", e: "🛣️" },
        { w: "rock", e: "🪨" },
        { w: "red", e: "🔴" },
        { w: "run", e: "🏃" },
        { w: "rice", e: "🍚" },
      ],
      middle: [
        { w: "carrot", e: "🥕" },
        { w: "parrot", e: "🦜" },
        { w: "pirate", e: "🏴‍☠️" },
        { w: "cherry", e: "🍒" },
        { w: "berry", e: "🫐" },
        { w: "giraffe", e: "🦒" },
        { w: "arrow", e: "🏹" },
        { w: "mirror", e: "🪞" },
        { w: "orange", e: "🍊" },
        { w: "zero", e: "0️⃣" },
        { w: "forest", e: "🌲" },
        { w: "cereal", e: "🥣" },
      ],
      end: [
        { w: "car", e: "🚗" },
        { w: "star", e: "⭐" },
        { w: "door", e: "🚪" },
        { w: "bear", e: "🐻" },
        { w: "chair", e: "🪑" },
        { w: "tiger", e: "🐯" },
        { w: "jar", e: "🫙" },
        { w: "four", e: "4️⃣" },
        { w: "ear", e: "👂" },
        { w: "hair", e: "💇" },
        { w: "guitar", e: "🎸" },
        { w: "dinosaur", e: "🦕" },
      ],
    },
    sentences: [
      "The red rabbit rides a rocket.",
      "Rory the robot draws a rainbow.",
      "A pirate parrot eats carrots.",
    ],
    story: {
      title: "Rocket Rabbit",
      lines: [
        "Rabbit builds a really red rocket.",
        "The rocket roars past the stars.",
        "Rabbit waves to a robot on Mars.",
        "Hooray for Rocket Rabbit!",
      ],
    },
  },
  {
    id: "s",
    sound: "S",
    name: "Snake Safari",
    emoji: "🐍",
    color: "#37C978",
    coach: "Sneaky snake — smile, teeth almost closed!",
    cue: {
      title: "The Snake Sound",
      lines: [
        "Smile big — teeth almost closed.",
        "Hide your tongue behind your teeth.",
        "Blow soft air: sss… like a sneaky snake!",
      ],
      drills: ["sah", "say", "see", "soh", "soo"],
    },
    listen: [
      { say: "sip", options: [{ w: "sip", e: "🥤" }, { w: "ship", e: "🚢" }] },
      { say: "mouse", options: [{ w: "mouse", e: "🐭" }, { w: "mouth", e: "👄" }] },
      { say: "sink", options: [{ w: "sink", e: "🚰" }, { w: "think", e: "🤔" }] },
      { say: "sun", options: [{ w: "sun", e: "☀️" }, { w: "run", e: "🏃" }] },
      { say: "sock", options: [{ w: "sock", e: "🧦" }, { w: "shock", e: "⚡" }] },
    ],
    words: {
      start: [
        { w: "sun", e: "☀️" },
        { w: "sock", e: "🧦" },
        { w: "soap", e: "🧼" },
        { w: "seal", e: "🦭" },
        { w: "soup", e: "🍜" },
        { w: "sand", e: "🏖️" },
        { w: "snake", e: "🐍" },
        { w: "star", e: "⭐" },
        { w: "six", e: "6️⃣" },
        { w: "seed", e: "🌱" },
        { w: "sail", e: "⛵" },
        { w: "smile", e: "😊" },
      ],
      middle: [
        { w: "dinosaur", e: "🦕" },
        { w: "pencil", e: "✏️" },
        { w: "baseball", e: "⚾" },
        { w: "glasses", e: "👓" },
        { w: "bicycle", e: "🚲" },
        { w: "castle", e: "🏰" },
        { w: "whistle", e: "🎵" },
        { w: "fossil", e: "🦴" },
        { w: "monster", e: "👾" },
        { w: "basket", e: "🧺" },
        { w: "racing", e: "🏎️" },
        { w: "messy", e: "🌪️" },
      ],
      end: [
        { w: "bus", e: "🚌" },
        { w: "house", e: "🏠" },
        { w: "mouse", e: "🐭" },
        { w: "grass", e: "🌿" },
        { w: "dress", e: "👗" },
        { w: "horse", e: "🐴" },
        { w: "goose", e: "🪿" },
        { w: "juice", e: "🧃" },
        { w: "face", e: "🙂" },
        { w: "ice", e: "🧊" },
        { w: "yes", e: "✅" },
        { w: "octopus", e: "🐙" },
      ],
    },
    sentences: [
      "Sam the seal sips soup by the sea.",
      "Six silly snakes sit in the sun.",
      "A mouse in socks slides down the grass.",
    ],
    story: {
      title: "Seal's Sandy Day",
      lines: [
        "Sam the seal sees the sunny sand.",
        "He slides down a slippery slope.",
        "A silly starfish says, 'So fast!'",
        "Sam smiles. What a super day!",
      ],
    },
  },
  {
    id: "l",
    sound: "L",
    name: "Lollipop Lagoon",
    emoji: "🍭",
    color: "#FFC53D",
    coach: "Tap the bump behind your top teeth — la la la!",
    cue: {
      title: "The La-La Tap",
      lines: [
        "Open your mouth a little.",
        "Tap your tongue tip on the bump behind your top teeth.",
        "Sing it: la la la… lll!",
      ],
      drills: ["lah", "lay", "lee", "loh", "loo"],
    },
    listen: [
      { say: "lock", options: [{ w: "lock", e: "🔒" }, { w: "rock", e: "🪨" }] },
      { say: "lamb", options: [{ w: "lamb", e: "🐑" }, { w: "ram", e: "🐏" }] },
      { say: "light", options: [{ w: "light", e: "💡" }, { w: "kite", e: "🪁" }] },
      { say: "log", options: [{ w: "log", e: "🪵" }, { w: "dog", e: "🐶" }] },
      { say: "leaf", options: [{ w: "leaf", e: "🍃" }, { w: "beef", e: "🥩" }] },
    ],
    words: {
      start: [
        { w: "lion", e: "🦁" },
        { w: "lemon", e: "🍋" },
        { w: "leaf", e: "🍃" },
        { w: "lock", e: "🔒" },
        { w: "ladder", e: "🪜" },
        { w: "lamp", e: "💡" },
        { w: "lake", e: "🏞️" },
        { w: "light", e: "💡" },
        { w: "lunch", e: "🍱" },
        { w: "love", e: "❤️" },
        { w: "lizard", e: "🦎" },
        { w: "lollipop", e: "🍭" },
      ],
      middle: [
        { w: "balloon", e: "🎈" },
        { w: "yellow", e: "💛" },
        { w: "elephant", e: "🐘" },
        { w: "umbrella", e: "☂️" },
        { w: "salad", e: "🥗" },
        { w: "dollar", e: "💵" },
        { w: "pillow", e: "🛏️" },
        { w: "jelly", e: "🍇" },
        { w: "helicopter", e: "🚁" },
        { w: "violin", e: "🎻" },
        { w: "melon", e: "🍈" },
        { w: "color", e: "🎨" },
      ],
      end: [
        { w: "ball", e: "⚽" },
        { w: "bell", e: "🔔" },
        { w: "owl", e: "🦉" },
        { w: "snail", e: "🐌" },
        { w: "whale", e: "🐳" },
        { w: "apple", e: "🍎" },
        { w: "bowl", e: "🥣" },
        { w: "seal", e: "🦭" },
        { w: "shell", e: "🐚" },
        { w: "pool", e: "🏊" },
        { w: "school", e: "🏫" },
        { w: "camel", e: "🐪" },
      ],
    },
    sentences: [
      "Lily the lion licks a lemon lollipop.",
      "A little llama loves yellow balloons.",
      "Look! An owl and a whale play ball.",
    ],
    story: {
      title: "The Lost Lollipop",
      lines: [
        "Lily the lion has a lemon lollipop.",
        "Splash! It falls in the lake.",
        "A lucky owl lifts it out.",
        "Lily laughs: 'I love you, lollipop!'",
      ],
    },
  },
  {
    id: "th",
    sound: "TH",
    name: "Thunder Theater",
    emoji: "⛈️",
    color: "#8F7BFF",
    coach: "Peek-a-boo tongue between your teeth!",
    cue: {
      title: "Peek-a-boo Tongue",
      lines: [
        "Stick your tongue tip between your teeth — peek-a-boo!",
        "Blow soft air over it: thhh…",
        "Check in a mirror — can you see your tongue?",
      ],
      drills: ["thumb", "three", "thin", "bath", "math"],
    },
    listen: [
      { say: "three", options: [{ w: "three", e: "3️⃣" }, { w: "tree", e: "🌳" }] },
      { say: "thumb", options: [{ w: "thumb", e: "👍" }, { w: "drum", e: "🥁" }] },
      { say: "mouth", options: [{ w: "mouth", e: "👄" }, { w: "mouse", e: "🐭" }] },
      { say: "bath", options: [{ w: "bath", e: "🛁" }, { w: "bat", e: "🦇" }] },
      { say: "think", options: [{ w: "think", e: "🤔" }, { w: "sink", e: "🚰" }] },
    ],
    words: {
      start: [
        { w: "thumb", e: "👍" },
        { w: "three", e: "3️⃣" },
        { w: "think", e: "🤔" },
        { w: "thunder", e: "⛈️" },
        { w: "thread", e: "🧵" },
        { w: "thirteen", e: "🔢" },
        { w: "thick", e: "📏" },
        { w: "thin", e: "📏" },
        { w: "thermos", e: "🧴" },
        { w: "theater", e: "🎭" },
        { w: "thirsty", e: "🥤" },
        { w: "thousand", e: "1️⃣0️⃣0️⃣0️⃣" },
      ],
      middle: [
        { w: "toothbrush", e: "🪥" },
        { w: "birthday", e: "🎂" },
        { w: "bathtub", e: "🛁" },
        { w: "panther", e: "🐈‍⬛" },
        { w: "feather", e: "🪶" },
        { w: "weather", e: "🌦️" },
        { w: "brother", e: "👦" },
        { w: "mother", e: "👩" },
        { w: "father", e: "👨" },
        { w: "something", e: "🎁" },
        { w: "nothing", e: "🚫" },
        { w: "python", e: "🐍" },
      ],
      end: [
        { w: "mouth", e: "👄" },
        { w: "teeth", e: "🦷" },
        { w: "bath", e: "🛁" },
        { w: "earth", e: "🌍" },
        { w: "math", e: "➕" },
        { w: "path", e: "🛤️" },
        { w: "both", e: "✌️" },
        { w: "tooth", e: "🦷" },
        { w: "moth", e: "🦋" },
        { w: "cloth", e: "🧵" },
        { w: "north", e: "🧭" },
        { w: "south", e: "🧭" },
      ],
    },
    sentences: [
      "Theo thinks three thumbs are funny.",
      "I brush my teeth on Thursday.",
      "Thea thanks her brother for the feather.",
    ],
    story: {
      title: "Three on Thursday",
      lines: [
        "Thea has a birthday on Thursday.",
        "Thunder booms — thump, thump!",
        "'Thank you, thunder!' Thea laughs.",
        "Then everybody thinks of cake.",
      ],
    },
  },
  {
    id: "sh",
    sound: "SH",
    name: "Shark Ship",
    emoji: "🦈",
    color: "#3FB6F0",
    coach: "Round your lips — shhh like a secret!",
    cue: {
      title: "The Quiet Sound",
      lines: [
        "Push your lips out in a little circle.",
        "Blow soft air: shhh…",
        "Like telling a secret: shhh!",
      ],
      drills: ["she", "shoe", "show", "shy", "shhh"],
    },
    listen: [
      { say: "ship", options: [{ w: "ship", e: "🚢" }, { w: "sip", e: "🥤" }] },
      { say: "shell", options: [{ w: "shell", e: "🐚" }, { w: "bell", e: "🔔" }] },
      { say: "sheep", options: [{ w: "sheep", e: "🐑" }, { w: "jeep", e: "🚙" }] },
      { say: "wash", options: [{ w: "wash", e: "🧼" }, { w: "watch", e: "⌚" }] },
      { say: "shark", options: [{ w: "shark", e: "🦈" }, { w: "dark", e: "🌑" }] },
    ],
    words: {
      start: [
        { w: "ship", e: "🚢" },
        { w: "shark", e: "🦈" },
        { w: "sheep", e: "🐑" },
        { w: "shell", e: "🐚" },
        { w: "shoe", e: "👟" },
        { w: "shirt", e: "👕" },
        { w: "shop", e: "🛒" },
        { w: "shadow", e: "🌑" },
        { w: "shape", e: "🔷" },
        { w: "shovel", e: "🪣" },
        { w: "shower", e: "🚿" },
        { w: "sugar", e: "🍬" },
      ],
      middle: [
        { w: "ocean", e: "🌊" },
        { w: "milkshake", e: "🥤" },
        { w: "fishing", e: "🎣" },
        { w: "dishes", e: "🍽️" },
        { w: "sunshine", e: "🌞" },
        { w: "washing", e: "🧺" },
        { w: "cushion", e: "🛋️" },
        { w: "spaceship", e: "🚀" },
        { w: "mushroom", e: "🍄" },
        { w: "flashlight", e: "🔦" },
        { w: "marshmallow", e: "🍡" },
        { w: "workshop", e: "🔧" },
      ],
      end: [
        { w: "fish", e: "🐟" },
        { w: "brush", e: "🖌️" },
        { w: "trash", e: "🗑️" },
        { w: "splash", e: "💦" },
        { w: "wish", e: "🌠" },
        { w: "shush", e: "🤫" },
        { w: "wash", e: "🧼" },
        { w: "push", e: "🫸" },
        { w: "bush", e: "🌳" },
        { w: "leash", e: "🐕" },
        { w: "crash", e: "💥" },
        { w: "finish", e: "🏁" },
      ],
    },
    sentences: [
      "The shy shark shares a shiny shell.",
      "A sheep in shoes shops for shirts.",
      "Shhh! The fish wish for a milkshake.",
    ],
    story: {
      title: "The Shiny Shell",
      lines: [
        "Sherman the shark finds a shiny shell.",
        "He shows the sheep on the ship.",
        "Splash! They share a milkshake.",
        "Shhh… the shell is sleeping.",
      ],
    },
  },
  {
    id: "ch",
    sound: "CH",
    name: "Cheetah Chase",
    emoji: "🐆",
    color: "#FF8A3D",
    coach: "Pop it like a choo-choo train — ch! ch!",
    cue: {
      title: "The Choo-Choo Sound",
      lines: [
        "Round your lips a little.",
        "Touch your tongue to the roof of your mouth…",
        "Pop it: ch! ch! Like a train: choo-choo!",
      ],
      drills: ["cha", "chee", "choo", "chow", "chew"],
    },
    listen: [
      { say: "chip", options: [{ w: "chip", e: "🍟" }, { w: "ship", e: "🚢" }] },
      { say: "chair", options: [{ w: "chair", e: "🪑" }, { w: "share", e: "🤝" }] },
      { say: "watch", options: [{ w: "watch", e: "⌚" }, { w: "wash", e: "🧼" }] },
      { say: "cheese", options: [{ w: "cheese", e: "🧀" }, { w: "keys", e: "🔑" }] },
      { say: "cherry", options: [{ w: "cherry", e: "🍒" }, { w: "berry", e: "🫐" }] },
    ],
    words: {
      start: [
        { w: "cheese", e: "🧀" },
        { w: "chair", e: "🪑" },
        { w: "cherry", e: "🍒" },
        { w: "chicken", e: "🐔" },
        { w: "chocolate", e: "🍫" },
        { w: "cheetah", e: "🐆" },
        { w: "chip", e: "🍟" },
        { w: "child", e: "🧒" },
        { w: "chin", e: "😊" },
        { w: "chop", e: "🪓" },
        { w: "cheer", e: "📣" },
        { w: "chain", e: "⛓️" },
        { w: "chalk", e: "✏️" },
        { w: "chest", e: "📦" },
      ],
      middle: [
        { w: "teacher", e: "🧑‍🏫" },
        { w: "kitchen", e: "🍳" },
        { w: "ketchup", e: "🍅" },
        { w: "lunchbox", e: "🍱" },
        { w: "catching", e: "🥎" },
        { w: "inches", e: "📏" },
        { w: "picture", e: "🖼️" },
        { w: "nature", e: "🌿" },
        { w: "adventure", e: "🗺️" },
        { w: "marching", e: "🥁" },
        { w: "richer", e: "💰" },
        { w: "hatchet", e: "🪓" },
      ],
      end: [
        { w: "peach", e: "🍑" },
        { w: "beach", e: "🏖️" },
        { w: "watch", e: "⌚" },
        { w: "sandwich", e: "🥪" },
        { w: "couch", e: "🛋️" },
        { w: "witch", e: "🧙" },
        { w: "lunch", e: "🍱" },
        { w: "branch", e: "🌳" },
        { w: "bench", e: "🪑" },
        { w: "match", e: "🔥" },
        { w: "catch", e: "⚾" },
        { w: "rich", e: "💎" },
      ],
    },
    sentences: [
      "Charlie the cheetah chews cheesy chips.",
      "The chicken checks the kitchen for chocolate.",
      "Watch the witch munch a sandwich!",
    ],
    story: {
      title: "Cheetah's Lunch",
      lines: [
        "Chad the cheetah checks his lunchbox.",
        "Cheese, chips, and a chocolate chunk!",
        "He munches on the beach — chomp, chomp!",
        "What a champion lunch!",
      ],
    },
  },
];
